student_project/student_app/urls.py
from django.urls import path
from .views import *

app_name = 'student_app'
urlpatterns = [
    path('', HomeView.as_view(), name = 'home'),
    path('expenses/', ExpenseView.as_view(), name = 'expense'),
    path("student-detail/<int:s_id>/", StudentDetailView.as_view(), name = 'student_detail'),

]

student_project/student_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("student_app.urls"))
]

student_project/student_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class Expense(models.Model):
    student = models.ForeignKey(Student, on_delete = models.CASCADE)
    amount = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.student.name

student_project/student_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from .models import *
from django.db.models import Avg, Count, Min, Sum
import json

class HomeView(TemplateView):
    template_name = 'home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["stud"] = Student.objects.all()
        return context

class ExpenseView(TemplateView):
    template_name = 'expense.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        expense = Expense.objects.all().order_by('-id')
        context["exp"] = expense

        total = 0
        for ex in expense:
            total += ex.amount
        context['total'] = total
        students  = Student.objects.all()[:4]
        label = []
        # label = ''
        data= []
        for s in students:
            # label += s.name + ","
            label.append(s.name)

            total_amount = Expense.objects.filter(student__name=s.name).aggregate(total=Sum('amount'))['total']
            data.append(total_amount)
        context['name'] = label
        # context['name1'] = label[0]
        # context['name2'] = label[1]
        # context['name3'] = label[2]
        # context['name4'] = label[3]

        context['data'] = list(data)



    
        return context

class StudentDetailView(TemplateView):
    template_name = 'expensedetail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        stud_id = self.kwargs['s_id']
        stud_obj = Student.objects.get(id = stud_id)
        context['student'] = stud_obj


        total = 0
        expense = Expense.objects.filter(student=stud_obj)
        for ex in expense:
            total += ex.amount
        context['total'] = total


        return context

    
    
    

student_project/templates/expense.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>expense</title>

</head>
<body>
    <ul>
      
        {% for expense in exp %}
        <li>
        Name = {{expense.student.name}}
        </li>
        <p>Amount = {{expense.amount}}</p>
        <p>Created-at = {{expense.created_at |timesince}} ago</p>
        {% endfor %}
        <p>Total = {{total}}</p>
        <p id="name">{{name}} </p>
        <p id='data'>{{data}}</p>
        <!-- {% for i in name %}
        {{i}}
        {% endfor %} -->

    </ul>
    <canvas id="barChart"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

    <script>
        var name = "{{name}}"
        name_split = name.split(",")
        console.log(typeof(name_split))
        console.log("name_split = " + name_split)


        // function clean(obj) {
        //     for (var propName in obj) {
        //         if (obj[propName] === null) {
        //             delete obj[propName];
        //         }
        //     }
        //     return obj
        // }
        // console.log(clean(name_split))
        // var myJSON = JSON.stringify(name_split);
        // console.log(typeof(myJSON))
        // console.log(myJSON)

        // var filter_name_split = myJSON.filter(function(el){
        //     return el != null
        // })
        // console.log(filter_name_split)
        // for(i=0; i<=name_split.length; i++){
        //     name_split[i] = name_split[i].replace(/^\s*/, "").replace(/\s*$/, "")
        //     console.log(name_split[i])
        //     console.log(typeof(name_split[i]))
        // }
            
        var chart = document.getElementById('barChart');
        // for(i = 0; i < mylist.length; i++){
        //     alert(mylist[i])
        // };


        // var name1 = '{{name1}}';
        // var name2 = '{{name2}}';
        // var name3 = '{{name3}}';
        // var name4 = '{{name4}}';
        var myPieChart = new Chart(chart, {
        
        type: 'pie',
        data: {
            labels : {{name|safe}},
            // labels : {{name}},

            datasets : [
                {
                    label:'Student',
                    backgroundClolor:["Red","Yellow", 'Green', 'Blue'],
                    data:{{data|safe}}
                }
            ]
        },
        });
        // console.log(typeof(myPieChart))
    
    </script>
</body>
</html>

student_project/templates/expensedetail.html
<h1> Student Detail page</h1>
{{student.name}}
{% for exp in student.expense_set.all %}
    <li>Expenses = {{exp.amount}}</li>
    <p>{{exp.created_at}}</p>
{% endfor %}
<p>Total = {{total}}</p>

student_project/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student</title>
</head>
<body>
    <h1>Home Page</h1>
    <a href="{% url 'student_app:expense' %}">All Expenses</a>
    {% for student in stud %}
    <h2><a href="{% url 'student_app:student_detail' student.id %}">{{student.name}}</a></h2>
    {% endfor %}
</body>
</html>